# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-03 05:10
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='batch',
            name='omr_baseline',
        ),
        migrations.RemoveField(
            model_name='batch',
            name='proc_baseline',
        ),
        migrations.AddField(
            model_name='batch',
            name='omr_baseline_1',
            field=models.FileField(default='', upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['csv'], 'Please upload valid CSV file')], verbose_name='Baseline 1'),
        ),
        migrations.AddField(
            model_name='batch',
            name='omr_baseline_2',
            field=models.FileField(default='', upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['csv'], 'Please upload valid CSV file')], verbose_name='Baseline 2'),
        ),
        migrations.AddField(
            model_name='batch',
            name='omr_counselling_feedback',
            field=models.FileField(default='', upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['csv'], 'Please upload valid CSV file')], verbose_name='Counselling and Student Feedback'),
        ),
        migrations.AddField(
            model_name='batch',
            name='proc_baseline_1',
            field=models.FileField(blank=True, help_text='Do not upload. This field will be auto updated.', upload_to='data/', validators=[django.core.validators.FileExtensionValidator(['csv'], 'Please upload valid CSV file')], verbose_name='Baseline 1'),
        ),
        migrations.AddField(
            model_name='batch',
            name='proc_baseline_2',
            field=models.FileField(blank=True, help_text='Do not upload. This field will be auto updated.', upload_to='data/', validators=[django.core.validators.FileExtensionValidator(['csv'], 'Please upload valid CSV file')], verbose_name='Baseline 2'),
        ),
        migrations.AddField(
            model_name='batch',
            name='proc_counselling_feedback',
            field=models.FileField(blank=True, help_text='Do not upload. This field will be auto updated.', upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['csv'], 'Please upload valid CSV file')], verbose_name='Counselling and Student Feedback'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='omr_career_aware',
            field=models.FileField(default='', upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['csv'], 'Please upload valid CSV file')], verbose_name='Career Awareness'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='omr_career_planning',
            field=models.FileField(default='', upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['csv'], 'Please upload valid CSV file')], verbose_name='Career Planning'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='omr_self_aware',
            field=models.FileField(default='', upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['csv'], 'Please upload valid CSV file')], verbose_name='Self Awareness'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.IntegerField(choices=[(1, 'Not Processed'), (2, 'Baseline Processed'), (3, 'Career Awareness Processed'), (4, 'Career Planning Processed'), (5, 'Self Awareness Processed'), (6, 'Transformation Completed')], default=1, help_text='Do not change. This field will be auto updated.'),
        ),
    ]
