# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-28 14:53
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0002_auto_20180803_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch',
            name='omr_counselling_feedback',
            field=models.FileField(blank=True, default='', upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['csv'], 'Please upload valid CSV file')], verbose_name='Counselling and Student Feedback'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.IntegerField(choices=[(1, 'Not Processed'), (2, 'Baseline 1 Processed'), (3, 'Baseline 2 Processed'), (4, 'Career Awareness Processed'), (5, 'Career Planning Processed'), (6, 'Self Awareness Processed'), (7, 'Counselling and Student Feedback Processed'), (8, 'Transformation Completed')], default=1, help_text='Do not change. This field will be auto updated.'),
        ),
    ]
