# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2019-08-08 17:42
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('batch', '0003_auto_20180828_2023'),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='batch',
            name='modified_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='batch',
            name='omr_follow_up_1_data',
            field=models.FileField(blank=True, default='', upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['csv'], 'Please upload valid CSV file')], verbose_name='Follow up 1 Data'),
        ),
        migrations.AddField(
            model_name='batch',
            name='omr_follow_up_2_data',
            field=models.FileField(blank=True, default='', upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['csv'], 'Please upload valid CSV file')], verbose_name='Follow up 2 Data'),
        ),
        migrations.AddField(
            model_name='batch',
            name='proc_follow_up_1_data',
            field=models.FileField(blank=True, help_text='Do not upload. This field will be auto updated.', upload_to='data/', validators=[django.core.validators.FileExtensionValidator(['csv'], 'Please upload valid CSV file')], verbose_name='Follow up 1 Data'),
        ),
        migrations.AddField(
            model_name='batch',
            name='proc_follow_up_2_data',
            field=models.FileField(blank=True, help_text='Do not upload. This field will be auto updated.', upload_to='data/', validators=[django.core.validators.FileExtensionValidator(['csv'], 'Please upload valid CSV file')], verbose_name='Follow up 2 Data'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='omr_baseline_1',
            field=models.FileField(blank=True, default='', upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['csv'], 'Please upload valid CSV file')], verbose_name='Baseline 1'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='omr_baseline_2',
            field=models.FileField(blank=True, default='', upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['csv'], 'Please upload valid CSV file')], verbose_name='Baseline 2'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='omr_career_aware',
            field=models.FileField(blank=True, default='', upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['csv'], 'Please upload valid CSV file')], verbose_name='Career Awareness'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='omr_career_planning',
            field=models.FileField(blank=True, default='', upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['csv'], 'Please upload valid CSV file')], verbose_name='Career Planning'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='omr_self_aware',
            field=models.FileField(blank=True, default='', upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['csv'], 'Please upload valid CSV file')], verbose_name='Self Awareness'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='proc_counselling_feedback',
            field=models.FileField(blank=True, help_text='Do not upload. This field will be auto updated.', upload_to='data/', validators=[django.core.validators.FileExtensionValidator(['csv'], 'Please upload valid CSV file')], verbose_name='Counselling and Student Feedback'),
        ),
        migrations.AlterField(
            model_name='batch',
            name='status',
            field=models.IntegerField(choices=[(1, 'Not Processed'), (2, 'Baseline 1 Processed'), (3, 'Baseline 2 Processed'), (4, 'Career Awareness Processed'), (5, 'Career Planning Processed'), (6, 'Self Awareness Processed'), (7, 'Counselling and Student Feedback Processed'), (8, 'Follow up 1 Data Processed'), (9, 'Follow up 2 Data Processed'), (10, 'Transformation Completed')], default=1, help_text='Do not change. This field will be auto updated.'),
        ),
    ]
